const initialiseBDB = () => {
  const buildings = [
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 1,
      xgid: [],
      name: "Woodcutter",
      cost: [40, 100, 50, 60],
      k: 1.67,
      cu: 2,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 2,
      xgid: [],
      name: "Clay Pit",
      cost: [80, 40, 80, 50],
      k: 1.67,
      cu: 2,
      cp: 1,
      maxLvl: 21,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 3,
      xgid: [],
      name: "Iron Mine",
      cost: [100, 80, 30, 60],
      k: 1.67,
      cu: 3,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 4,
      xgid: [],
      name: "Cropland",
      cost: [70, 90, 70, 20],
      k: 1.67,
      cu: 0,
      cp: 1,
      maxLvl: 21,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 5,
      xgid: [5],
      name: "Sawmill",
      cost: [520, 380, 290, 90],
      k: 1.8,
      cu: 4,
      cp: 1,
      maxLvl: 5,
      breq: [
        { gid: 1, lvl: 10 },
        { gid: 15, lvl: 5 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 6,
      xgid: [6],
      name: "Brickyard",
      cost: [440, 480, 320, 50],
      k: 1.8,
      cu: 3,
      cp: 1,
      maxLvl: 5,
      breq: [
        { gid: 2, lvl: 10 },
        { gid: 15, lvl: 5 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 7,
      xgid: [7],
      name: "Iron Foundry",
      cost: [200, 450, 510, 120],
      k: 1.8,
      cu: 6,
      cp: 1,
      maxLvl: 5,
      breq: [
        { gid: 3, lvl: 10 },
        { gid: 15, lvl: 5 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 8,
      xgid: [8],
      name: "Grain Mill",
      cost: [500, 440, 380, 1240],
      k: 1.8,
      cu: 3,
      cp: 1,
      maxLvl: 5,
      breq: [{ gid: 4, lvl: 5 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 9,
      xgid: [9],
      name: "Bakery",
      cost: [1200, 1480, 870, 1600],
      k: 1.8,
      cu: 4,
      cp: 1,
      maxLvl: 5,
      breq: [
        { gid: 4, lvl: 10 },
        { gid: 8, lvl: 5 },
        { gid: 15, lvl: 5 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 10,
      xgid: [],
      name: "Warehouse",
      cost: [130, 160, 90, 40],
      k: 1.28,
      cu: 1,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 1 }],
      req: { multi: true },
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 11,
      xgid: [],
      name: "Granary",
      cost: [80, 100, 70, 20],
      k: 1.28,
      cu: 1,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 1 }],
      req: { multi: true },
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 12,
      xgid: [],
      name: "Smithy",
      cost: [170, 200, 380, 130],
      k: 1.28,
      cu: 4,
      cp: 2,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 3 },
        { gid: 22, lvl: 3 },
      ],
      req: { version: [0, 3] },
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 13,
      xgid: [13],
      name: "Armoury",
      cost: [130, 210, 410, 130],
      k: 1.28,
      cu: 4,
      cp: 2,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 3 },
        { gid: 22, lvl: 1 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 14,
      xgid: [14],
      name: "Tournament Square",
      cost: [1750, 2250, 1530, 240],
      k: 1.28,
      cu: 1,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 16, lvl: 15 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 15,
      xgid: [15],
      name: "Main Building",
      cost: [70, 40, 60, 20],
      k: 1.28,
      cu: 2,
      cp: 2,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 16,
      xgid: [16],
      name: "Rally Point",
      cost: [110, 160, 90, 70],
      k: 1.28,
      cu: 1,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 17,
      xgid: [17],
      name: "Marketplace",
      cost: [80, 70, 120, 70],
      k: 1.28,
      cu: 4,
      cp: 3,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 3 },
        { gid: 10, lvl: 1 },
        { gid: 11, lvl: 1 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 18,
      xgid: [18],
      name: "Embassy",
      cost: [180, 130, 150, 80],
      k: 1.28,
      cu: 3,
      cp: 4,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 1 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 19,
      xgid: [19],
      name: "Barracks",
      cost: [210, 140, 260, 120],
      k: 1.28,
      cu: 4,
      cp: 1,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 3 },
        { gid: 16, lvl: 1 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 20,
      xgid: [20],
      name: "Stable",
      cost: [260, 140, 220, 100],
      k: 1.28,
      cu: 5,
      cp: 2,
      maxLvl: 20,
      breq: [
        { gid: 12, lvl: 3 },
        { gid: 22, lvl: 5 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 21,
      xgid: [21],
      name: "Workshop",
      cost: [460, 510, 600, 320],
      k: 1.28,
      cu: 3,
      cp: 3,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 5 },
        { gid: 22, lvl: 10 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 22,
      xgid: [22],
      name: "Academy",
      cost: [220, 160, 90, 40],
      k: 1.28,
      cu: 4,
      cp: 4,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 3 },
        { gid: 19, lvl: 3 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 23,
      xgid: [],
      name: "Cranny",
      cost: [40, 50, 30, 10],
      k: 1.28,
      cu: 0,
      cp: 1,
      maxLvl: 10,
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 24,
      xgid: [24],
      name: "Town Hall",
      cost: [1250, 1110, 1260, 600],
      k: 1.28,
      cu: 4,
      cp: 5,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 10 },
        { gid: 22, lvl: 10 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 25,
      xgid: [25, 26, 44],
      name: "Residence",
      cost: [580, 460, 350, 180],
      k: 1.28,
      cu: 1,
      cp: 2,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 5 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 26,
      xgid: [26, 25, 44],
      name: "Palace",
      cost: [550, 800, 750, 250],
      k: 1.28,
      cu: 1,
      cp: 5,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 5 },
        { gid: 18, lvl: 1 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 27,
      xgid: [27],
      name: "Treasury",
      cost: [2880, 2740, 2580, 990],
      k: 1.26,
      cu: 4,
      cp: 6,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 10 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 28,
      xgid: [28],
      name: "Trade Office",
      cost: [1400, 1330, 1200, 400],
      k: 1.28,
      cu: 3,
      cp: 3,
      maxLvl: 20,
      breq: [
        { gid: 17, lvl: 20 },
        { gid: 20, lvl: 10 },
      ],
    },
    {
      xcap: true,
      cap: false,
      tribe: 0,
      gid: 29,
      xgid: [29],
      name: "Great Barracks",
      cost: [630, 420, 780, 360],
      k: 1.28,
      cu: 4,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 19, lvl: 20 }],
    },
    {
      xcap: true,
      cap: false,
      tribe: 0,
      gid: 30,
      xgid: [30],
      name: "Great Stable",
      cost: [780, 420, 660, 300],
      k: 1.28,
      cu: 5,
      cp: 2,
      maxLvl: 20,
      breq: [{ gid: 20, lvl: 20 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 1,
      gid: 31,
      xgid: [31],
      name: "City Wall",
      cost: [70, 90, 170, 70],
      k: 1.28,
      cu: 0,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 2,
      gid: 32,
      xgid: [32],
      name: "Earth Wall",
      cost: [120, 200, 0, 80],
      k: 1.28,
      cu: 0,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 3,
      gid: 33,
      xgid: [33],
      name: "Palisade",
      cost: [160, 100, 80, 60],
      k: 1.28,
      cu: 0,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: false,
      cap: true,
      tribe: 0,
      gid: 34,
      xgid: [34],
      name: "Stonemason",
      cost: [155, 130, 125, 70],
      k: 1.28,
      cu: 2,
      cp: 1,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 5 },
        { gid: 26, lvl: 3 },
      ],
    },
    {
      xcap: false,
      cap: true,
      tribe: 2,
      gid: 35,
      xgid: [35],
      name: "Brewery",
      cost: [1460, 930, 1250, 1740],
      k: 1.4,
      cu: 6,
      cp: 4,
      maxLvl: 10,
      breq: [
        { gid: 11, lvl: 20 },
        { gid: 16, lvl: 10 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 3,
      gid: 36,
      xgid: [36],
      name: "Trapper",
      cost: [100, 100, 100, 100],
      k: 1.28,
      cu: 4,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 16, lvl: 1 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 37,
      xgid: [37],
      name: "Hero's Mansion",
      cost: [700, 670, 700, 240],
      k: 1.33,
      cu: 2,
      cp: 1,
      maxLvl: 20,
      breq: [
        { gid: 15, lvl: 3 },
        { gid: 16, lvl: 1 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 38,
      xgid: [],
      name: "Great Warehouse",
      cost: [650, 800, 450, 200],
      k: 1.28,
      cu: 1,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 10 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 39,
      xgid: [],
      name: "Great Granary",
      cost: [400, 500, 350, 100],
      k: 1.28,
      cu: 1,
      cp: 1,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 10 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 40,
      xgid: [40],
      name: "Wonder of the World",
      cost: [66700, 69050, 72200, 13200],
      k: 1.0275,
      cu: 1,
      cp: 0,
      maxLvl: 100,
      cost100: [1e6, 1e6, 1e6, 193630],
    },
    {
      xcap: true,
      cap: true,
      tribe: 1,
      gid: 41,
      xgid: [41],
      name: "Horse Drinking Trough",
      cost: [780, 420, 660, 540],
      k: 1.28,
      cu: 5,
      cp: 3,
      maxLvl: 20,
      breq: [
        { gid: 16, lvl: 10 },
        { gid: 20, lvl: 20 },
      ],
    },
    {
      xcap: true,
      cap: true,
      tribe: 4,
      gid: 42,
      xgid: [42],
      name: "Stone Wall",
      cost: [110, 160, 70, 60],
      k: 1.28,
      cu: 0,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 5,
      gid: 43,
      xgid: [43],
      name: "Makeshift Wall",
      cost: [50, 80, 40, 30],
      k: 1.28,
      cu: 0,
      cp: 1,
      maxLvl: 20,
    },
    {
      xcap: true,
      cap: true,
      tribe: 5,
      gid: 44,
      xgid: [25, 26, 44],
      name: "Command Center",
      cost: [1600, 1250, 1050, 200],
      k: 1.22,
      cu: 1,
      cp: 2,
      maxLvl: 20,
      breq: [{ gid: 15, lvl: 5 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 4,
      gid: 45,
      xgid: [45],
      name: "Waterworks",
      cost: [910, 945, 910, 340],
      k: 1.31,
      cu: 1,
      cp: 2,
      maxLvl: 20,
      breq: [{ gid: 37, lvl: 10 }],
    },
    {
      xcap: true,
      cap: true,
      tribe: 0,
      gid: 46,
      xgid: [46],
      name: "Hospital",
      cost: [320, 280, 420, 360],
      k: 1.28,
      cu: 3,
      cp: 4,
      maxLvl: 20,
      breq: [
        { gid: 22, lvl: 15 },
        { gid: 15, lvl: 10 },
      ],
    },
  ];

  function RoundMul(v, n) {
    return Math.round(v / n) * n;
  }

  function TimeT3(a, k, b) {
    this.a = a;
    if (arguments.length < 3) {
      this.k = 1.16;
      if (arguments.length === 1) {
        k = 1;
      }
      this.b = 1875 * k;
    } else {
      this.k = k;
      this.b = b;
    }
  }

  function getStat(gid, lvl) {
    building = buildings[gid - 1];
    let cost = building.cost.map((v) =>
      RoundMul(v * Math.pow(building.k, lvl - 1), 5)
    );
    if (building.gid == 40) {
      cost = cost.map((value) => Math.min(value, 1e6));
    }
    let cu = building.cu;
    cu = lvl != 1 ? Math.round((5 * cu + lvl - 1) / 10) : cu;
    return {
      cost: cost,
      cu: cu,
    };
  }

  return {
    stats: getStat,
    name: (gid) => buildings[gid - 1].name,
    data: (gid) => buildings[gid - 1],
    gidFromName: (n) => buildings.find((o) => o.name === n).gid,
  };
};

const BDB = initialiseBDB();
